### ISSUE TITLE
When i run the application on eclipse it throws NoSuchFieldException

### ISSUE THREAD

**Issue by bewithme** [klevis/frauddetection#1]
Exception in thread "main" java.lang.NoSuchFieldException: theCaseInsensitiveEnvironment
	at java.lang.Class.getDeclaredField(Class.java:2070)
	at ramo.klevis.ml.fraud.Run.setHadoopHomeEnvironmentVariable(Run.java:107)
	at ramo.klevis.ml.fraud.Run.main(Run.java:43)

**Comment by bewithme** [comment]
can you implement this application with Neural Networks ?

**Comment by klevis** [comment]
@bewithme when run on other machines than windows please comment out setHadoopHomeEnvironmentVariable method. That is meant to make hadoop available to java application on windows without installing hadoop. However on other OS you can freely remove that method but the hadoop must be installed on the OS so java app will be able to find require libaries.

**Comment by bewithme** [comment]
thank you so much！

发自我的 iPhone

**Comment by bewithme** [comment]
How to 

发自我的 iPhone
